# Generated by Django 3.2.5 on 2021-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='notify',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
